### ISSUE TITLE
Default firmware using 98% of space

### ISSUE THREAD

**Issue by wizche** [AnaviTechnology/anavi-macro-pad-8#1]
I was trying to customize my macro pad 8 and noticed the following warning when building:
```
 The firmware size is approaching the maximum - 28284/28672 (98%, 388 bytes free)
```

I wanted to build some macros (https://beta.docs.qmk.fm/using-qmk/advanced-keycodes/feature_macros) but those wouldn't fit the chip. Is there something I can do to get more bytes in order to add some `SEND_STRING` commands? Or am I doing something completely wrong here?

Full log:
```
$ qmk compile -kb anavi/macropad8 -km default
Ψ Compiling keymap with make -j 1 anavi/macropad8:default

QMK Firmware 0.12.20
Making anavi/macropad8 with keymap default

avr-gcc (GCC) 5.4.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Size before:
   text    data     bss     dec     hex filename
      0   28938       0   28938    710a .build/anavi_macropad8_default.hex

Compiling: keyboards/anavi/macropad8/keymaps/default/keymap.c                                       [OK]
Linking: .build/anavi_macropad8_default.elf                                                         [OK]
Creating load file for flashing: .build/anavi_macropad8_default.hex                                 [OK]
Copying anavi_macropad8_default.hex to qmk_firmware folder                                          [OK]
Checking file size of anavi_macropad8_default.hex                                                   [WARNINGS]

 * The firmware size is approaching the maximum - 28284/28672 (98%, 388 bytes free)
```

**Comment by leon-anavi** [comment]
Hi @wizche,

Sorry for the late reply, the easiest way to reduce the QMK firmware size for ANAVI Macro Pad 8 it to cut some of the RGB Lighting animations and effects.

For example, in your custom keymap you can create `config.h` in the keymap directory that overwrites the main `config.h` with a reduced number of supported RGB Lighting animations and effects:

```
#pragma once

#undef RGBLIGHT_ANIMATIONS
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_CHRISTMAS
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_SNAKE
```

I am working on a git keymap for ANAVI Macro Pad 8 which contain this example to reduce the overall firmware size.

Best regards,
Leon

**Comment by leon-anavi** [comment]
Hi @wizche,

There hasn't been any traction on this topic for quite some time so I will close it. The [git keymap is part of the upstream of the QMK firmware and can be used as an example](https://github.com/qmk/qmk_firmware/tree/master/keyboards/anavi/macropad8/keymaps/git).

Thank you for using ANAVI Macro Pad 8 and your contributions, happy new year and best wishes for 2023!

Thanks,
Leon
