### ISSUE TITLE
I2C interface is not implemented correctly

### ISSUE THREAD

**Issue by HeikoLau** [AnaviTechnology/anavi-macro-pad-8#4]
### The resistors R13 and R14 have too large values

The I2C happens to work with the 0.9" OLED supplied. Due to the two 4.7k series resistors, the AVR cannot drive the voltage level to 0V. Nevertheless, the OLED recognises the transmission and sends an ACK. Since the OLED drives the SDA line without series resistors, 0V is reached (SCL=blue curve, SDA=red curve).
<img width="817" alt="OLED 0 9" src="https://user-images.githubusercontent.com/11643051/204803461-6cceec54-4eb6-405b-a48e-e6a227b58155.png">

This does not work with another OLED display (1.3"). The transmission is not even recognised by the OLED and the ACK is missing.
<img width="654" alt="OLED 1 3" src="https://user-images.githubusercontent.com/11643051/204803466-c74ee54a-f7b9-498e-b948-1108a5aee0dc.png">

The two series resistors in SCL and SDA must be reduced to a maximum of 100 ohms.

### Pull-up resistors are missing

The waveform of SCL and SDA is too slow in the transition from LOW to HIGH. This is caused by missing pull-up resistors. Usually 2.2k are used.

**Comment by leon-anavi** [comment]
Hi @HeikoLau,

Thank you for reporting this hardware issue. I have modified the KiCad project to set  the values of the protection resistors used in series on the SDA and SCL lines of the I2C to 24 Ohm. As you noted there are no pull-up resistors so the I2C breakout boards, including these with an OLED display, should take care for them.

Sorry for my late reply on this topic and thank you again for the feedback. In the git commit message I have pointed you out in a `Reported-by:` git trailer. 

Thank you for valuable contribution and best wishes for the new year!

Thanks,
Leon
